[project]
name = "bedding-order-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.14.3",
    "openpyxl>=3.1.5",
    "pywebview>=6.2.1",
    "sentence-transformers>=5.6.1",
]

[project.scripts]
bedding-order-parser = "bedding_order_parser:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.21.0",
    "pytest>=9.1.1",
]
